### ISSUE TITLE
Instructions do not mention dependancies

### ISSUE THREAD

**Issue by jurassicjordan** [qweryty/image-ai-utils-server#2]
dependancies diffusers, colorlog, esrgan, dotenv, and possibly others are not mentioned in the readme instructions.

**Comment by qweryty** [comment]
If you are on linux, the dependencies are installed by using `poetry install` command. On windows they are prepackaged.
Do you have any specific error?

**Comment by agustincaniglia** [comment]
Hello. I got through the guide and then main.exe finishes it closes.
I am on windows.
If I run python main.py on anaconda prompt I get the following:
(base) H:\DESCARGAS 1TB\image_ai_utils_windows\uvicorn>python main.py
Traceback (most recent call last):
File "H:\DESCARGAS 1TB\image_ai_utils_windows\uvicorn\main.py", line 1, in <module>
import asyncio
File "C:\Users\acani\anaconda3\lib\asyncio\__init__.py", line 8, in <module>
from .base_events import *
File "C:\Users\acani\anaconda3\lib\asyncio\base_events.py", line 18, in <module>
import concurrent.futures
File "C:\Users\acani\anaconda3\lib\concurrent\futures\__init__.py", line 8, in <module>
from concurrent.futures._base import (FIRST_COMPLETED,
File "C:\Users\acani\anaconda3\lib\concurrent\futures\_base.py", line 7, in <module>
import logging
File "H:\DESCARGAS 1TB\image_ai_utils_windows\uvicorn\logging.py", line 17, in <module>
class ColourizedFormatter(logging.Formatter):
AttributeError: partially initialized module 'logging' has no attribute 'Formatter' (most likely due to a circular import)

Also I don't know if it might be something related to the user and password of the edited env, but I don't know what that login is supoosed to be so didn't know what to edit there.. Thanks.

**Comment by qweryty** [comment]
Hi! Thanks for taking your time to report your issues.

Can you try running main.exe from command line and post the logs here? Most probable scenario is that you just don't have enough vram(for now it uses non optimized version of stable diffusion, an optimized version is a planned feature)

Those `main.py` files from release archive are just from dependencies and not for server itself. If you want to try running it from source code, you should download another archive which says "Source code" and try following the linux manual, the process is almost the same for windows, except the `source .vevn/bin/activate` becomes `.venv\Scripts\activate` and you use `copy` command instead of `cp` command

User and password settings are there for security reasons if you decide to host the server on separate machine, so only you can access it, on local installation you can leave them as is(I will update the README.md to make it more clear).

**Comment by qweryty** [comment]
@agustincaniglia Created a separate issue #3

**Comment by agustincaniglia** [comment]
Here is what I get on Main now before it shutts down:
![mainexe](https://user-images.githubusercontent.com/25101051/188455993-65e22e23-6f19-43b2-ace5-27ecd0c73b38.png)

**Comment by jurassicjordan** [comment]
I was able to install the dependancies, I may have done the installation out of order so I am going to close this issue since its working fine now
